dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: tTh64m+l8A9N/iKW6HR36ZYKEpk7iZ2NZfs4ZXbzjFSgNRzLYRiicvhRF1rsMXaaeFfWFHcbs3sI1pspiuIcnU/cVI1Jz5ElNXnKmSxJNiLlHh8uiNbOGFdGvmwxVkqQb2VLKedXKvgg73mOkK0h2oUUu/VK4NU1n4rQVZYPhEUmGzrKRa/AbHDr55WrGRp0fHjm31xW2cpmscw++OHKsKZjVQpczk3jlfmLm8Usk+yDsjCIGpMmRz6G/o/15ptQh3FKXsbsZUBjOJWLV7r1OKw926FTr6ggwBwW9hRxStPgftOpE801apFeC2m5R6IJo0XoYh80TUsazfPNdoGdQy+grJPRtMcKzNYB3VWYFKGBp9Xkn+Psh9ucFfjPjgrSww9PBhQcOs0gVk8MY9eLpGLamcylA260LjfHK3SiG9v6SnppuKhwoNX2fGFijGwkEDLObI9dFW8hefINNQ4GS5HdT0e2iaIijS9eq/jYfpuVuLguYlto6bQCQwPEa2SuL8nYbaMGuRsEb10Kgjw5P9XNX/YcaiwW20LwaoZha13WZTHcpsttDyTkrHtdJkenGSoPxwG6tuKCOLvRsJg7XjxIMY/23GOzyD/0WxAecDiR57PL9K5rv/YvuwmSXtZq3z3lwW1sGeXyvHcLGWrxPs5EgYsFTOlkTM01dN6i4xw=
