- name: Configure app
  hosts: app
  become: true
  tasks:
    - copy: src=files/puma.service dest=/etc/systemd/system/puma.service
      notify: reload puma
    - name: Add config for DB conection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser
    - systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
